allowBuilds:
  sharp: true
  unrs-resolver: true
  "@tailwindcss/oxide": true
  "@prisma/engines": true
  prisma: true
  "@prisma/client": true
  msw: false
  "@google/genai": set this to true or false
  protobufjs: set this to true or false
